### ISSUE TITLE
[MRESOLVER-66] Settings task does not load active profile repositories defined in settings.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resolver-ant-tasks#66]
**[lefebvre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jflefebvre)** opened **[MRESOLVER-66](https://issues.apache.org/jira/browse/MRESOLVER-66?redirect=false)** and commented

my-settings.xml :

```xml
 <?xml version="1.0"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
 http://maven.apache.org/xsd/settings-1.0.0.xsd">

<interactiveMode>false</interactiveMode>

<servers>
 <server>
 <id>my-repo</id>
 <configuration>
 <httpHeaders>
 <property>
 <name>Private-Token</name>
 <value>XXX</value>
 </property>
 </httpHeaders>
 </configuration>
 </server>
 </servers>

<profiles>
 <profile>
 <id>enable-repos</id>
 <repositories>
 <repository>
 <id>central</id>
 <name>central</name>
 <url>http://repo1.maven.org/maven2</url>
 </repository>
 <repository>
 <id>my-repo</id>
 <name>my repository</name>
 <url>XXX</url>
 </repository>
 </repositories>
 </profile>
 </profiles>

<activeProfiles>
 <activeProfile>enable-repos</activeProfile>
 </activeProfiles>
</settings>
```

 

`<settings file="my-settings.xml" globalfile="my-settings.xml"/>`

 

The resolver task does not try to resolve artifacts using "my-repo".

---

**Affects:** ant-tasks-1.2.1

**Attachments:**
- [MRESOLVER-66.log](https://issues.apache.org/jira/secure/attachment/12965612/MRESOLVER-66.log) (_381.13 kB_)
- [MRESOLVER-66.xml](https://issues.apache.org/jira/secure/attachment/12965613/MRESOLVER-66.xml) (_1024 bytes_)

**Remote Links:**
- [GitHub Pull Request #3
](https://github.com/apache/maven-resolver-ant-tasks/pull/3)
- [GitHub Pull Request #4
](https://github.com/apache/maven-resolver-ant-tasks/pull/4)
- [GitHub Pull Request #791
](https://github.com/apache/maven-resolver/issues/791)

1 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Provide some debug output from Ant.

**Comment by jira-importer** [comment]
**[lefebvre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jflefebvre)** commented

Hello,

 

Debug Output attached : MRESOLVER-66.log

As you can see, ant resolver try to resolve my artifdact from central but not from my-repo :

 

D:\ATELIER\01.core\bin\MRESOLVER-66\MRESOLVER-66.xml:18: Could not resolve artifacts: Could not find artifact org.jugbb.ant:jugbbant:jar:1.7 in central (http://repo1.maven.org/maven2/)
at org.apache.maven.resolver.internal.ant.tasks.Resolve.execute(Resolve.java:166)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
at org.apache.tools.ant.Main.runBuild(Main.java:834)
at org.apache.tools.ant.Main.startAnt(Main.java:223)
at org.apache.tools.ant.Main.start(Main.java:190)
at org.apache.tools.ant.Main.main(Main.java:274)
Caused by: org.apache.maven.resolver.internal.ant.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.jugbb.ant:jugbbant:jar:1.7 in central (http://repo1.maven.org/maven2/)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:268)
at org.apache.maven.resolver.internal.ant.tasks.Resolve.execute(Resolve.java:160)
... 17 more
Caused by: org.apache.maven.resolver.internal.ant.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jugbb.ant:jugbbant:jar:1.7 in central (http://repo1.maven.org/maven2/)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
at org.apache.maven.resolver.internal.ant.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
... 20 more

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Have you tried to create a repo group in Nexus and us that as mirror in your settings.xml? This works for me.

**Comment by jira-importer** [comment]
**[lefebvre](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jflefebvre)** commented

No I have not tried because I'm not using Nexus. All artifacts are hosted into gitlab https://docs.gitlab.com/ee/user/project/packages/maven_repository.html

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I can confirm this and I have no idea how to fix that. Does this happen with Maven directly?

**Comment by jira-importer** [comment]
**[Patrick Buchheit](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pbtura)** commented

Did anyone every find a solution to this? I'm having the same issue. It's not just the explicit settings task either. I have tried adding the remote repo to the default settings file and to the pom itself. ant-maven-resolver ignores all of them and uses central. If I try running maven directly with the same settings everything works.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Branch MRESOLVER-66 has been pushed, have a look.
